### ISSUE TITLE
House Collision Bug

### ISSUE THREAD

**Issue by YukoSakura6** [meadowriders/MDR-Public#2]
Expected behavior: Houses having collision stopping the player from bugging in.
Current behavior: Houses collision being too poor and player being able to flow through them.
Media: The last report has the link.
Reproduce: Start running up a houses stair and soon enough you will flow through.
Operating System: Win10
RAM: 16GB
Available Storage: 2TB
Graphics Card: NVIDIA GeForce GTX 1050 Ti
Processor: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by vars1ty** [comment]
This will probably never be 100% fixed, due to how poorly Unity treats collision and other things.

One custom fix which will arrive in the next release can be seen [here](https://streamable.com/vlults) though, where you can see the horse not being able to clip into objects anymore.
