### ISSUE TITLE
Gpu fan ramps up to 200% when grass is beng rendered

### ISSUE THREAD

**Issue by div1de** [meadowriders/MDR-Public#4]
The fan shouldnt be ramping up to full speed

When grass is visible, gpu turns into what can only be described as a broken lawnmower mixed with a jet engine with how loud it is

![image](https://user-images.githubusercontent.com/114225663/192661441-73bb3f56-dfae-435c-be63-7fa277828105.png)

Steps to reproduce the issue

1. Walk around
2. Go to where grass is not visible
3. Go back to grass and notice your gpu ran ramp up

> Operating System: Windows 11 unfortunately

> Memory (RAM): 32GB DDR4

> Available Storage: 500gb

> Graphics Card: Radeon RX6500XT

> Processor: Ryzen 5 5600G

**Comment by vars1ty** [comment]
Fixed in c2603ff2, from 160~ FPS to 413~ FPS
