### ISSUE TITLE
Full on yeeted into the air when you walk backwards

### ISSUE THREAD

**Issue by Cheat-Dev** [meadowriders/MDR-Public#5]
When you walk backwards, you teleport, and when walking backwards holding a or d, you yeet into the air like you jumped on a trampoline

1. Walk backwards
2. Hold down any left or right key

> Operating System: Arch Linux

> Memory (RAM): 32GB DDR4

> Available Storage: 500GB

> Graphics Card: RX6500XT

> Processor: R5 5600G

Discord: foren.#7624

**Comment by vars1ty** [comment]
Probably happens due to root motion, will fix when the player controller rework happens.

**Comment by vars1ty** [comment]
Never mind, seems to be connected with the new engine version which caused this too: #6
